name: Deploy
on:
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"
  push:
    branches:
      - master

# env:

jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: tag_name

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build API
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_WORKSPACE}
          echo ${{ steps.tag_name.outputs.tag }}
          echo ${{ github.run_number }}
          echo 
          echo ${{ github.event.inputs.caption }}
          echo "Build API"
          sleep 10s
          chmod +x "./test.sh"
          ./test.sh