name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: format('Run for {0} ', 'release-2021.06.02')
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo ${GITHUB_REF}
          echo "Build API"
          sleep 10s