name: Deploy
on:
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"
  push:
    branches:
      - master
jobs:
  description: ${{ github.event.inputs.caption }}
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo ${GITHUB_REF}
          echo "Build API"
          sleep 10s