name: Deploy
on:
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"
  push:
    branches:
      - master
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build API
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_WORKSPACE}
          echo ${{ github.event.inputs.caption }}
          echo "Build API"
          sleep 10s
          chmod +x "./test.sh"
          ./test.sh